= JEE Testcontainers

image::https://api.bintray.com/packages/t1/javaee-helpers/jee-testcontainers/images/download.svg[link="https://bintray.com/t1/javaee-helpers/jee-testcontainers/_latestVersion"]

Simply start and stop Jakarta EE containers and deploy applications for your integration tests. This is an extension to https://testcontainers.org[Testcontainers] for Jakarta EE application servers, so Docker is used under the hood, but you don't need to write, e.g., a Dockerfile.

Prototypical Example:

[source,java]
---------------------------------------------------------------
@Testcontainers
public class MyAppIT {
    @Container static JeeContainer CONTAINER = JeeContainer.create()
        .withDeployment("target/my-app.war");

    @Test void shouldGetJolokiaResponse() {
        String body = CONTAINER.target().request(APPLICATION_JSON_TYPE).get(String.class);

        assertThat(body).isEqualTo("{\"status\":\"okay\"}");
    }
}
---------------------------------------------------------------

The console output of the container is piped to the test's output, STDOUT in green and STDERR in blue.

== Deployments

As seen in the prototypical example above, you can install an application by calling `.withDeployment(<file>)`.

Instead of a local file, you can also install from an URL. Or you can use a maven URN like `urn:mvn:org.jolokia:jolokia-war-unsecured:1.6.3:war`. Note that in this case, the file already has to be downloaded manually to you local maven repository... I plan to fix that; tell me if you need it.

== Configuration

Set the system property `jee-testcontainer` to one of the following keys to select the corresponding container. Ideally you shouldn't have to care about what server your application runs on, or you may even want to test it in multiple containers. Then you can run your test suite in your CI pipeline with different system properties.

[options="header",cols="15%,15%,40%,30%"]
|=======================
| Key | Container | Docker Image | Notes
| wildfly | https://wildfly.org[WildFly] | `quay.io/wildfly/wildfly-centos7` | default
| open-liberty | https://openliberty.io[Open Liberty] | `open-liberty` from Docker Hub |
// TODO support | tom-ee |  |  |
// TODO support | payara |  |  |
// TODO support | glassfish |  |  |
|=======================

It's quite straight forward to support other containers. It's even easier to make the images or versions (tags) configurable. Pull request are warmly welcome, but even if you just open an issue, I may find the time, too.

// TODO health wait strategy
// TODO use different images or versions/tags via system property
// TODO actually do the mvn download instead: mvn dependency:get -Dartifact=org.jolokia:jolokia-war:1.3.7:war

== Limitations

You can't currently configure your application, e.g. by adding data sources. I will add that when I need it, which may be very soon ;-)
