name: Java CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 17 ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Pre-fetch wunderbar.demo.order:2.4.9 # so it's in `~/.m2/repository`
      run: mvn --batch-mode mvn dependency:get -Dartifact=com.github.t1:wunderbar.demo.order:2.4.9:war
    - name: Build with Maven
      run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install
