name: Java CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11, 17 ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Pre-fetch jolokia 1.6.2 # so JeeContainerBehavior.LocalFileUrl can access a file directly
      run: mvn --batch-mode dependency:get -Dartifact=org.jolokia:jolokia-war-unsecured:1.6.2:war
    - name: Build with Maven
      run: mvn --batch-mode verify
